# Wallust Kitty Template

# --- THE FIXED BACKGROUND ---
# This ensures your background is ALWAYS #2f2f2f regardless of the wallpaper
background #2f2f2f
background_opacity 0.60

# --- THE TEXT (Foreground) ---
# Use color7 (usually a bright grey/white) so it's always readable
foreground #ffffff

# --- THE ACCENTS (The 16 colors) ---
# These will still change based on your wallpaper for syntax highlighting
color0  #414142
color1  #252427
color2  #282629
color3  #9E9FA0
color4  #B1A2A9
color5  #BCBDBF
color6  #F5E0E9
color7  #F2E7EC
color8  #A9A2A5

# Input text Color
color9  #e0e0e0

color10 #282629
color11 #9E9FA0
color12 #B1A2A9
color13 #BCBDBF
color14 #F5E0E9
color15 #F2E7EC

# Selection colors
selection_foreground #1A1A1B
selection_background #F2E7EC

# Cursor
cursor #F2E7EC