# Wallust Kitty Template

# --- THE FIXED BACKGROUND ---
# This ensures your background is ALWAYS #2f2f2f regardless of the wallpaper
background #2f2f2f
background_opacity 0.60

# --- THE TEXT (Foreground) ---
# Use color7 (usually a bright grey/white) so it's always readable
foreground #ffffff

# --- THE ACCENTS (The 16 colors) ---
# These will still change based on your wallpaper for syntax highlighting
color0  #3F3737
color1  #290303
color2  #2C0404
color3  #360E0C
color4  #541A1F
color5  #C68D72
color6  #FBBB97
color7  #F4D5C2
color8  #AB9588

# Input text Color
color9  #e0e0e0

color10 #2C0404
color11 #360E0C
color12 #541A1F
color13 #C68D72
color14 #FBBB97
color15 #F4D5C2

# Selection colors
selection_foreground #170E0E
selection_background #F4D5C2

# Cursor
cursor #F4D5C2