# Start the wallpaper daemon
exec-once = swww-daemon

# Start Quickshell
exec-once = quickshell




# Restore the last wallpaper you picked in the Waypaper GUI
exec-once = waypaper --restore


exec-once = ~/nixos-dotfiles/config/scripts/swww-wallust-executer.sh